
project_id = "vioaqyclkyrhoutysjmh"

[api]
# Enable all necessary APIs
enabled_apis = ["rest", "auth", "storage", "realtime", "functions"]
port = 54321

[auth]
# The base URL for your website - this should match your deployed URL
site_url = "https://vioaqyclkyrhoutysjmh.lovable.app"
# Additional redirect URLs
additional_redirect_urls = ["http://localhost:3000", "http://localhost:3000/**", "https://localhost:3000/**", "capacitor://localhost:3000/**", "https://*.lovable.app/**", "https://vioaqyclkyrhoutysjmh.supabase.co/auth/v1/callback"]
# Token expiry time
jwt_expiry = 3600
# Allow new user signups
enable_signup = true
# Require email confirmation
enable_confirmations = true

[auth.email]
# Allow signups via email
enable_signup = true
# Require email confirmation on both old and new emails when changing
double_confirm_changes = true
# Require email confirmation
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
