
project_id = "vioaqyclkyrhoutysjmh"

[api]
# Disable Postgres server-side requests for the API
enabled_apis = ["rest", "auth", "storage", "realtime", "functions"]
port = 54321

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["http://localhost:3000/**", "https://localhost:3000/**", "capacitor://localhost:3000/**"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
